server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: 'C:\\Users\\hiddaoui\\Desktop\\Books\\Spring-microservices-in-action\\configserver\\src\\main\\resources\\config\\licensingservice\\licensingservice.yaml'